### PR TITLE
Bulk insert batches to database destinations

### PR DESCRIPTION
**Pull request by thizzle**
Issue bulk INSERT statements using the entire buffer, when writing to database destinations, for efficiency.

Also, don't quote null values.

### CODE REVIEW

**Comment by thizzle** [comment]
Please review, @acaloiaro @mtoneil

**Comment by mtoneil** [comment]
Overall seems fine to me. Is this for writing to redshift? I'm concerned even batch inserting rows will be an order of magnitude slower than doing the copy with s3 file.

**Comment by thizzle** [comment]
No, this change will only apply to writes to the postgres (RDS) database instance. Redshift loads will continue to use S3 -> COPY.

**Comment by mtoneil** [comment]
Ah ok. I guess this is because RDS can't do a COPY. Booo

**Comment by thizzle** [comment]
Yes. Boo, indeed. Just wait until you see the hoops I had to jump through to drop and restore foreign keys on tables because RDS won't let me drop system triggers. :)

**Pull request merged**
